refactored_version
Star-Academy/Team1-Codes pull request #1
Opened 2020-08-03 12:51 UTC by MJSahebnasi

2020-08-03 13:17 UTC, mohammadhheidarzade reviewed
سه تابع مربوط به کوئری باید در کلاس سرچ باشن و اصن ربطی به کلاس اینورتداینکس ندارن. کلاس سرچ هم خیلی بزرگ میشه اینطوری.برای درست کردنش چون ۳ تا تایپ مختلف در کوئری ها داریم میتونید یه کلاس جدید درست کنید که فرایند جدا سازی کوئری رو در اون انجام بدید.کامنت گزاری کم بود در کد. استفاده از منابع و کتابخانه ها خوب بود چیزی اضافه ای استفاده نکردین.موفق باشین

2020-08-03 14:06 UTC, MJavadHzr reviewed
کد خوانایی بود ولی همونطور که محمد حیدرزاده اشاره کرد میشه ورودی ها رو تو یه کلاس جدا پروسس کرد

2020-08-03 14:08 UTC, MJavadHzr commented on src/Phase01-Search/Search.java
> +            result = queryInfo.andDocs;
این قسمت رو هم نتونستم تشخیص بدم چرا اینجوری پیاده سازی شده

2020-08-03 14:20 UTC, MahdiHma requested changes
با کمی تغییرات می‌توانید کد را بهینه کنید کامنت گذاری هم باعث خوانایی بیشتر کد می‌شود.
در کل خوب و تمیز بود و نیاز به کمی تغییرات اشاره شده دارد. خدا قوت. موفق باشید.

2020-08-03 14:20 UTC, MahdiHma commented on src/Phase01-Search/InvertedIndex.java
> +        allWords = new HashMap<>();
این قسمت می‌تواند در کانستراکتور اتفاق بیفتد.

2020-08-03 14:20 UTC, MahdiHma commented on src/Phase01-Search/Search.java
> +
این قسمت از کلاس و البته کد های پایین تر از آن امکان جدا شدن از کلاس و تقسیم به بخش های کوچکتر را دارند

2020-08-03 14:24 UTC, titansarus commented on src/Phase01-Search/FileReader.java
>  import java.nio.file.Path;
دو تا از این ایمپورت ها به نظر استفاده نشده هستن که میشه حذفشون کرد.

2020-08-03 14:32 UTC, titansarus commented on src/Phase01-Search/Search.java
> +        if (!queryInfo.seenAnOrDoc)
فکر کنم این جا طبق این لینک:
https://refactoring.guru/replace-nested-conditional-with-guard-clauses
نیاز به ریفکتور داره.
معمولا برای یک مورد باشه، این که
result
تعریف کنید و بریزید داخلش و تهش ریترن کنید، اوکیه ولی این جا خیلی حالت ها زیاد شدن و همون جا
return 
تا این که متغیر جدا تعریف کنید و در نهایت
return
اش کنید..

2020-08-03 18:38 UTC, MJSahebnasi commented
> سه تابع مربوط به کوئری باید در کلاس سرچ باشن و اصن ربطی به کلاس اینورتداینکس ندارن. کلاس سرچ هم خیلی بزرگ میشه اینطوری.برای درست کردنش چون ۳ تا تایپ مختلف در کوئری ها داریم میتونید یه کلاس جدید درست کنید که فرایند جدا سازی کوئری رو در اون انجام بدید.کامنت گزاری کم بود در کد. استفاده از منابع و کتابخانه ها خوب بود چیزی اضافه ای استفاده نکردین.موفق باشین

راستش با مورد اول موافق نیستم. این متد ها 
get()
هایی هستن که جای یک کوئری، چند تا رو میگیرن و به نظرم مناسب ترین جا براشون همون جاست

یک کلاس جدید از کلاس سرچ استخراج کردیم که کارای کوئری ها اونجا انجام میشه

چند جا که به نظر لازم بود کامنت گذاشتیم

2020-08-03 18:41 UTC, MJSahebnasi commented on src/Phase01-Search/Search.java
> +            result = queryInfo.andDocs;
کامنت اضافه شد

2020-08-03 19:27 UTC, MJSahebnasi commented on src/Phase01-Search/Search.java
> +            result = queryInfo.andDocs;
کامنت اضافه شد

2020-08-03 19:31 UTC, MJSahebnasi commented on src/Phase01-Search/InvertedIndex.java
> +        allWords = new HashMap<>();
ممنون
درستش کردیم

2020-08-03 19:33 UTC, MJSahebnasi commented on src/Phase01-Search/Search.java
> +
کلاس جدید استخراج شد

2020-08-03 19:34 UTC, AlirezaT99 commented on src/Phase01-Search/FileReader.java
>  import java.nio.file.Path;
بله حذف شدن

2020-08-03 20:34 UTC, AlirezaT99 commented on src/Phase01-Search/Search.java
> +        if (!queryInfo.seenAnOrDoc)
ممنون. البته اینجا در ادامه‌ی تابع بازم عملیات باید روی
result
انجام شه و هنوز نمیشه توی شرط ها
return
کرد

2020-08-03 20:55 UTC, mahdimalverdi approved these changes

2020-08-03 21:10 UTC, ahmadsalimi commented on src/Phase01-Search/SearchQuery.java
> +    }
<div dir="rtl">

بنظرم به جای این که این کار رو بکنین،‌ بهتره که اینجا یک کلاس جدا بشه، منظورم اینه که این کلاس هندل بکنه سرچ کردن رو و ارتباط با inverted index رو، از طرفی همه‌ی این data ها هم تو یک کلاس دیگه (مثلا به اسم Query) باشن و به ازای هر Query، اون کلاس new بشه، کلا خیلی جالب نیست که تک تک این فیلد ها رو از اول new کنیم.

</div>

2020-08-03 21:10 UTC, ahmadsalimi commented on src/Phase01-Search/SearchQuery.java
> +    }
<div dir="rtl">

درواقع عملیات ساختن و پراسس query رو هم تو همون کلاس باید انجام بدید

</div>

2020-08-04 04:15 UTC, mohammadhheidarzade approved these changes

2020-08-04 05:07 UTC, alrz1999 requested changes

2020-08-04 05:07 UTC, alrz1999 commented on src/Phase01-Search/FileReader.java
> +    public ArrayList<String> getTokens(String filePath) throws IOException {
بهتره این تابع بره تو یه کلاس دیگه چون با 
Single Responsibility
بودن این کلاس در تضاده

2020-08-04 05:07 UTC, alrz1999 commented on src/Phase01-Search/InvertedIndex.java
> +    FileReader fileReader;
شاید بهتر باشه به جای فایل ریدر خود داکیومنت ها به این کلاس داده بشه

2020-08-04 05:07 UTC, alrz1999 commented on src/Phase01-Search/InvertedIndex.java
> +    public void initMap() {
این تابع هم به نظر میاد کاری که انجام میده به کلاس 
InvertedIndex
ربطی نداره

2020-08-04 05:07 UTC, alrz1999 commented on src/Phase01-Search/Search.java
> +    static void printResult(HashSet<String> result) {
بهتره یه کلاس برای نشان دادم خروجی داشته باشیم

2020-08-04 06:08 UTC, titansarus approved these changes

2020-08-04 07:01 UTC, MJSahebnasi commented on src/Phase01-Search/SearchQuery.java
> +    }
ممنون از دقتت
یه کلاس جدید استخراج کردیم

2020-08-04 07:31 UTC, AlirezaT99 commented on src/Phase01-Search/FileReader.java
> +    public ArrayList<String> getTokens(String filePath) throws IOException {
حق با شماست. اصلاح شد

2020-08-04 07:31 UTC, AlirezaT99 commented on src/Phase01-Search/InvertedIndex.java
> +    FileReader fileReader;
درسته.. اصلاح شد

2020-08-04 07:32 UTC, AlirezaT99 commented on src/Phase01-Search/InvertedIndex.java
> +    public void initMap() {
همراه سایر تغییرات، این نکته هم اوکی شد

2020-08-04 07:32 UTC, MJSahebnasi commented on src/Phase01-Search/Search.java
> +    static void printResult(HashSet<String> result) {
ممنون از پیشنهادت
این متد رو به یک کلاس مرتبط تر منتقلش کردیم

2020-08-04 07:56 UTC, Danyal0096 approved these changes
سلام
کد تمیزی بود و خب دوست داشتم خوانا و تمیز بود فقط یه نکته کوچیک هست که با اینکه نکته ریزی هست اما به نظرم مهمه که به قولی مایندستت اصلاح بشه اونم اینه که من با خوندن تابع درایورت (همون مین) باید بفهمم کد به صورت کلی داره چیکار میکنه و چی میخواد و خب من درایور رو خوندم دیدم بعد پراسس کردن کوئری دیگه هیچی نیست و این ذهنیت برام ایجاد میشه که برنامت قراره یه سرچ کوئری رو پراسس کنه و نه بیشتر و خب اینجا خروجی دادن به کاربر گم شده و در اصل تو دل همون پراسس اتفاق میافته و ساده ترین کاری که میشه کرد اینه که بقل اون پراسس کامنت بزنی که پراسسینگ اند اوت پوتینگ همونطور که گفتم نکته ناچیزیه اما به نظرم اصلاح خواستگاهش مهم بود

2020-08-04 08:37 UTC, alrz1999 approved these changes

2020-08-04 08:56 UTC, MJavadHzr approved these changes

2020-08-04 10:24 UTC, kimianoorbakhsh reviewed
خیلی کد خوب و تمیزی بود، چند نکته به نظرم اومد که نوشتم. موفق باشید.

2020-08-04 10:24 UTC, kimianoorbakhsh commented on src/Phase01-Search/FileReader.java
> +                    .map(String::valueOf).collect(Collectors.toCollection(HashSet::new));
صرفا برای زیبایی کد میگم اینو، فک کنم اگه اینشکلی باشه بهتره و فهمش هم یه کم راحت تر میکنه:
`Files.walk(Paths.get(folderPath))

.filter(Files::isRegularFile)

.map(Path::getFileName)

.map(String::valueOf)

.collect(Collectors.toCollection(HashSet::new));`
یعنی منظورم اینه که هر کدام از اون دات ها در خط جداگانه ای باشند.

2020-08-04 10:24 UTC, kimianoorbakhsh commented on src/Phase01-Search/InvertedIndex.java
>      public HashSet<String> andQueryResult(ArrayList<String> andQueries) {
شاید اگه این تابع توی یه کلاس دیگه مثل مثلا 
Arithmetic
بود، بهتر بود.

2020-08-04 10:32 UTC, MahdiHma approved these changes
خیلی عالی. خداقوت و موفق باشید :)

2020-08-04 15:20 UTC, AlirezaT99 commented on src/Phase01-Search/FileReader.java
> +                    .map(String::valueOf).collect(Collectors.toCollection(HashSet::new));
درسته. ممنون

2020-08-04 15:21 UTC, AlirezaT99 commented on src/Phase01-Search/InvertedIndex.java
>      public HashSet<String> andQueryResult(ArrayList<String> andQueries) {
بله حق با شماست..

2020-08-04 15:21 UTC, merged