Feature/unit test
Star-Academy/Team1-Codes pull request #2
Opened 2020-08-05 10:51 UTC by AlirezaT99

2020-08-05 15:13 UTC, titansarus commented on src/search/Query.java
> +    public ArrayList<String> excQueries;
این جا و چند جای دیگه، مگه با
Getter Setter
هندل نمیشه کرد که
public
گذاشتین؟ یعنی دلیل خاصی داره این کار به جای استفاده از گتر ستر؟

2020-08-05 15:19 UTC, titansarus commented on src/search/test/QueryTest.java
> +        query.invertedIndex.allWords.put("or1", docs1);
میشد به جای ساختن
InvertedIndex
و مقدار دهی تک تک حالتاش
یک
Map
ساخت و بعد رفتار
InvertedIndex
رو
Mock
کنید با کتابخونه که مثلا هر جایی این مقادیر لازم می شه، اون مپ رو برگردونه.
این جوری اگر در آینده بخواهید منطق
Inverted Index
رو توسعه بدین که چون بخش الگوریتمی مسئله هم هست، ممکنه انجام بشه یک روزی و توسعه دادنش دور از ذهن نیست، تست های
Query
 به خود
Inverted Index
وابستگی پیدا نمی کنن که فیل بشن و فقط تست های خود
Inverted Index
در اون زمان باید اوکی بشن.

2020-08-05 16:26 UTC, AlirezaT99 commented on src/search/Query.java
> +    public ArrayList<String> excQueries;
نه درست میگی.. اصلاحشون کردم

2020-08-06 10:15 UTC, AlirezaT99 commented on src/search/test/QueryTest.java
> +        query.invertedIndex.allWords.put("or1", docs1);
<div dir="rtl">
ممنون از کامنتت. با `Mockito` اوکی شد اون بخش..
</div>

2020-08-06 10:21 UTC, titansarus approved these changes

2020-08-06 10:50 UTC, AlirezaT99 commented
closes Star-Academy/codestar-intern-issues#39

2020-08-08 16:42 UTC, alrz1999 requested changes

2020-08-08 16:42 UTC, alrz1999 commented on src/search/test/FileReaderTest.java
> +    public void tokenizeLinesTest() {
فک کنم این تست واسه اینجا نیست و بهتره 
Tokenizer 
رو از 
FileReader
بیارین بیرون

2020-08-08 19:12 UTC, mahdimalverdi requested changes

2020-08-08 19:12 UTC, mahdimalverdi commented on src/search/FileReader.java
>          for (String line : fileLines) {
رجکس رو به عنوان یه شی استاتیک تعریف کنید
چون کامپایل رجکس خیلی کنده و این درست نیس که همیشه کامپایل بشه

2020-08-08 19:12 UTC, mahdimalverdi commented on src/search/QueryResult.java
> +                return null;
هیچ وقت نال بر نگردونید!
مگر شرایط خیلی خاص

2020-08-09 06:14 UTC, AlirezaT99 commented on src/search/test/FileReaderTest.java
> +    public void tokenizeLinesTest() {
انجام شد

2020-08-09 06:14 UTC, AlirezaT99 commented on src/search/FileReader.java
>          for (String line : fileLines) {
انجام شد

2020-08-09 06:36 UTC, MJSahebnasi commented on src/search/QueryResult.java
> +                return null;
null object
اضافه شد

2020-08-09 06:51 UTC, mahdimalverdi approved these changes

2020-08-09 08:12 UTC, alrz1999 approved these changes

2020-08-09 16:27 UTC, merged