C# search
Star-Academy/Team1-Codes pull request #4
Opened 2020-08-15 08:59 UTC by MJSahebnasi

2020-08-15 12:09 UTC, titansarus commented on C#/SearchLibrary/SearchLibrary.Test/AllFilesReaderTest.cs
> +            var actualNames = allFilesReader.getAllFilesNames();
این متود این جا
getAllFilesNames
عه
داخل کلاسش
GetAllFilesNames

فکر کنم حین ریفکتور اشتباهی این حرفش کوچیک شده و الآن ران نمیشد برای من که عوضش کردم اوکی شد..

2020-08-15 12:10 UTC, titansarus commented on C#/SearchLibrary/SearchLibrary.Test/AllFilesReaderTest.cs
> +            var expectedOneTokens = new List<string> {"unit", "test", "feature", "branch"};
این استفاده نشده.

2020-08-15 12:29 UTC, AlirezaT99 commented on C#/SearchLibrary/SearchLibrary.Test/AllFilesReaderTest.cs
> +            var actualNames = allFilesReader.getAllFilesNames();
آره مرسی درست شد

2020-08-15 12:30 UTC, AlirezaT99 commented on C#/SearchLibrary/SearchLibrary.Test/AllFilesReaderTest.cs
> +            var expectedOneTokens = new List<string> {"unit", "test", "feature", "branch"};
ممنون آره اوکی شد

2020-08-15 13:09 UTC, titansarus approved these changes

2020-08-16 02:30 UTC, mahdimalverdi requested changes

2020-08-16 02:30 UTC, mahdimalverdi commented on C#/SearchLibrary/SearchLibrary/Doc.cs
> +        public Doc()
کانستراکتور اول کلاس باشه قبل از پراپرتی ها

2020-08-16 02:30 UTC, mahdimalverdi commented on C#/SearchLibrary/SearchLibrary/InvertedIndex.cs
> +        public virtual HashSet<string> AllFilesNames { get; protected set; }
چرا ویرژوال؟

2020-08-16 02:30 UTC, mahdimalverdi commented on C#/SearchLibrary/SearchLibrary/InvertedIndex.cs
> +            AllFilesNames = new HashSet<string>(allFiles.Keys);
چرا از ToHashSet استفاده نشده؟

2020-08-16 02:30 UTC, mahdimalverdi commented on C#/SearchLibrary/SearchLibrary/QueryProcessor.cs
> +            foreach (var word in words)
من اگه بودم اینجوری می نوشتم

```CSharp
var orQueries = GetQueries('+');
var excQueries = GetQueries('-');
var andQueries = words.Where(w => w[0] != '-' && w[0] != '+').ToList();
...
private List<string> GetQueries(char starChar)
{
 return words.Where(w => w[0] == starChar).Select(w => w.Substring(1)).ToList();
}

```

2020-08-16 02:30 UTC, mahdimalverdi commented on C#/SearchLibrary/SearchLibrary/QueryProcessor.cs
> +                if (invertedIndex.Map.TryGetValue(word, out temp))
out var temp

2020-08-16 02:30 UTC, mahdimalverdi commented on C#/SearchLibrary/SearchLibrary/QueryProcessor.cs
> +            foreach (var word in query.AndQueries)
هر کدوم از فورایچ ها یه تابع بشه

2020-08-16 02:30 UTC, mahdimalverdi commented on C#/SearchLibrary/SearchLibrary/ReadFiles/AllFilesReader.cs
> +            var filePaths = Directory.GetFiles(documentsPath, "*.txt", SearchOption.AllDirectories);
"*.txt" به یه کانست تبدیل بشه تو کلاس
کلا هر چی رشته و عدد دارید به کانست توی کلاس تبدیل  کنید

2020-08-16 06:15 UTC, MJSahebnasi commented on C#/SearchLibrary/SearchLibrary/InvertedIndex.cs
> +        public virtual HashSet<string> AllFilesNames { get; protected set; }
واسه moq

2020-08-16 07:28 UTC, MJSahebnasi commented on C#/SearchLibrary/SearchLibrary/InvertedIndex.cs
> +            AllFilesNames = new HashSet<string>(allFiles.Keys);
مزیتش چیه؟

2020-08-16 08:18 UTC, mahdimalverdi commented on C#/SearchLibrary/SearchLibrary/InvertedIndex.cs
> +            AllFilesNames = new HashSet<string>(allFiles.Keys);
اینه که کدتون خوانا تر میشه
کلا همیشه از Linq استفاده بکنید

2020-08-16 08:19 UTC, mahdimalverdi approved these changes

2020-08-16 08:24 UTC, MJavadHzr commented on C#/SearchLibrary/SearchLibrary.Test/FileReaderTest.cs
> +            var actualContent = fileReader.GetContent(TestDocumentsPath + "\\Team.txt");
"\\Team.txt"
میتونه یا تو همون کانستنتی که دارین باشه یا هم جدا به صورت یه کانستنت تعریف بشه و اینجا جمع بشه

2020-08-16 08:24 UTC, MJavadHzr commented on C#/SearchLibrary/SearchLibrary.Test/InvertedIndexTest.cs
> +                    };
این قسمت رو میشه تو یه تابع مثلا
CreateExpected
گذاشت که خوانایی بیشتر بشه

2020-08-16 08:24 UTC, MJavadHzr commented on C#/SearchLibrary/SearchLibrary.Test/QueryProcessorTest.cs
> +
این جا چرا از همون
queryProcessor
خود کلاس استفاده نشده و یه شی جدید ساختین؟

2020-08-16 08:24 UTC, MJavadHzr commented on C#/SearchLibrary/SearchLibrary/InvertedIndex.cs
> +        }
این قسمت رو هم فکر کنم بشه اینطوری نوشت
` allFiles.ForEach(f => StoreTokens(f.Key, f.Value));`

2020-08-16 08:24 UTC, MJavadHzr commented on C#/SearchLibrary/SearchLibrary/ReadFiles/Tokenizer.cs
> +        }
**پیشنهاد :**
میشه از تابع
Split
هم استفاده کرد که ویژگی های جالبی داره

2020-08-16 08:33 UTC, mohammadhheidarzade approved these changes
به غیر از چند نکته که خیلی جزئی بودن موردی به نظرم نیومد موفق باشید. عالی بود :+1:

2020-08-16 08:33 UTC, mohammadhheidarzade commented on C#/SearchLibrary/SearchLibrary.Test/AllFilesReaderTest.cs
> +        AllFilesReader allFilesReader = new AllFilesReader(TestDocumentsPath);
استفاده به جا از
const
بهتر بود 
private
بشن گمون نکنم جای دیگه ازشون استفاده بشه

2020-08-16 08:33 UTC, mohammadhheidarzade commented on C#/SearchLibrary/SearchLibrary.Test/FileReaderTest.cs
> +        FileReader fileReader = new FileReader();
پرایوت باشن بهتره

2020-08-16 08:33 UTC, mohammadhheidarzade commented on C#/SearchLibrary/SearchLibrary.Test/InvertedIndexTest.cs
> +            List<string> value = new List<string> { "word1", "word2" };
از 
var
استفاده کنید اینجا :)

2020-08-16 08:33 UTC, mohammadhheidarzade commented on C#/SearchLibrary/SearchLibrary.Test/QueryProcessorTest.cs
> +            };
تست کامل :+1:

2020-08-16 08:52 UTC, MJSahebnasi commented on C#/SearchLibrary/SearchLibrary.Test/QueryProcessorTest.cs
> +
oops

2020-08-16 09:01 UTC, AlirezaT99 commented on C#/SearchLibrary/SearchLibrary/InvertedIndex.cs
> +        }
<div dir="rtl">
شدنو میشه ولی نمیدونم چقدر کار بهتری باشه :-" انگار یجاهایی گفته بودن foreach معمولی اینجاها بهتره..
</div>

2020-08-16 10:08 UTC, MJavadHzr commented on C#/SearchLibrary/SearchLibrary/InvertedIndex.cs
> +        }
آها اوکیه پس 👌🏻

2020-08-16 10:11 UTC, MJavadHzr approved these changes
عااالی خسته نباشید

2020-08-16 15:07 UTC, ahmadsalimi approved these changes

2020-08-17 04:26 UTC, alrz1999 approved these changes

2020-08-17 05:23 UTC, merged