Phase08
Star-Academy/Team1-Codes pull request #6
Opened 2020-08-24 12:18 UTC by AlirezaT99

closes https://github.com/Star-Academy/codestar-intern-issues/issues/84

2020-08-24 13:52 UTC, titansarus commented on C#/SearchNest/SearchNest.Test/DataReaderTest.cs
> +using Xunit;
using System
به نظر اضافیه و میشه حذفش کرد.

2020-08-24 14:05 UTC, titansarus commented on C#/SearchNest/SearchNest/ElasticClientManager.cs
> +            var connectionSettings = new ConnectionSettings(uri);
این آدرس
localhost
رو به نظرم به صورت یک استرینگ
constant
یا مثلا
readonly
بیرونش تعریف کنید، بهتره.

2020-08-24 14:06 UTC, titansarus approved these changes

2020-08-24 14:46 UTC, MJavadHzr approved these changes
عاالی، نکته خاصی به نظرم نرسید
خسته نباشید
👌🏻

2020-08-26 05:31 UTC, alrz1999 commented on C#/SearchNest/SearchNest/QueryHandler.cs
> +        private static QueryDescriptor BuildQuery(string rawQuery)
فک کنم بعضی از این تابعا یه
static
اضافه دارن

2020-08-26 05:31 UTC, alrz1999 approved these changes

2020-08-26 10:46 UTC, mahdimalverdi requested changes

2020-08-26 10:46 UTC, mahdimalverdi commented on C#/SearchNest/SearchNest/ElasticClientManager.cs
> +    internal static class ElasticClientManager
https://refactoring.guru/design-patterns/singleton/csharp/example

اینجوری بنویس اگه می خوای از دیزاین پترن سینگلتون استفاده بکنی

2020-08-26 10:46 UTC, mahdimalverdi commented on C#/SearchNest/SearchNest/QueryHandler.cs
> +        private static QueryDescriptor BuildQuery(string rawQuery)
نه اوکیه تابعی که به عناصر داخلی یه کلاس دسترسی نداره بهتره استاتیک باشه

2020-08-26 15:23 UTC, AlirezaT99 commented on C#/SearchNest/SearchNest/ElasticClientManager.cs
> +    internal static class ElasticClientManager
ممنون.. الان فکر کنم بهتر شده

2020-08-29 13:38 UTC, mahdimalverdi approved these changes

2020-08-31 10:26 UTC, merged